### ISSUE TITLE
Cannot find infix operators

### ISSUE THREAD

**Issue by mihanus** [fwcd/curry-language-server#52]
In source code like `[1,2] ++ [3,4]`, hovering `++` shows the type, but when trying to go the definition, it shows `No definition found`. However, in code like `(++) [1,2] [3,4]`, it works.

**Comment by fwcd** [comment]
Interestingly this only seems to be an issue in expressions, in functional patterns, go-to-definition works fine on infix operators:

```curry
last (_ ++ [x]) = x
```
