### ISSUE TITLE
Interface for module Prelude not found

### ISSUE THREAD

**Issue by hyperswine** [fwcd/curry-language-server#65]
![Screenshot 2023-12-05 at 5 02 23 am](https://github.com/fwcd/curry-language-server/assets/8978635/0bf0a745-69df-4d28-8a5a-edfad7ae86c8)

It also says this

![Screenshot 2023-12-05 at 5 04 20 am](https://github.com/fwcd/curry-language-server/assets/8978635/34627d8e-edb7-4c6b-be8f-20f89dcca406)

Im getting this error on a fresh `cypm new` template. Not entirely sure what the problem is, any ideas?

Extra details:
M1 MacOS 14.1.2
Using PAKCS 3.6.1-b1 of 2023-11-16 (swi 9.0)

**Comment by hyperswine** [comment]
okay, so it seems I didnt run pakcs to generate a .curry. Running it worked

**Comment by fwcd** [comment]
Glad it works for you!

Just curious, how did you configure VSCode to hide the title bar like on your first screenshot?

**Comment by hyperswine** [comment]
> Glad it works for you!
> 
> Just curious, how did you configure VSCode to hide the title bar like on your first screenshot?

https://marketplace.visualstudio.com/items?itemName=drcika.apc-extension

This extension. Just add to settings.json

```json
"apc.electron": {
      "titleBarStyle": "hidden",
    },
    "window.titleBarStyle": "native"
```
